version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    environment:
      MYSQL_HOST: db  # This is important to ensure Docker app connects to the correct DB
      MYSQL_USER: root
      MYSQL_PASSWORD: strr@123
      MYSQL_DATABASE: strr_app
      MYSQL_PORT: 3306  # Specify port, optional since it's the default MySQL port
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: strr@123
      MYSQL_DATABASE: strr_app
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d/  # Mount the init folder
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
